### ISSUE TITLE
all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by Sh4d1** [micro/kubernetes#11]
Hey! 

I have a problem. I'm trying to use micro on Kubernetes. Here are the usefull deployments:
For micro:
```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: micro
spec:
    replicas: 1
    selector:
        matchLabels:
            app: micro
    template:
        metadata:
            labels:
                app: micro
        spec:
            containers:
            - name: micro
              image: microhq/micro:kubernetes
              args:
                - "api"
                - "--handler=rpc"
                - "--namespace=wat"
              env:
              - name: MICRO_API_ADDRESS
                value: ":80"
              ports:
              - containerPort: 80
                name: micro-port
---
apiVersion: v1
kind: Service
metadata:
    name: micro
spec:
    selector:
        app: micro
    ports:
    - name: micro-api-http
      port: 80
      targetPort: micro-port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: micro
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
      - host: "api.wat.ptrk.io"
        http:
            paths:
                - path: /
                  backend:
                      serviceName: micro
                      servicePort: micro-api-http
```

For my service:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - name: user-service
                  image: sh4d1/wat-user-service
                  command: [
                      "./wat-user-service",
                      "--selector=static",
                      "--server_address=:8080"
                  ]
                  ports:
                      - containerPort: 8080
                        name: user-port
---
apiVersion: v1
kind: Service
metadata:
    name: user
    labels:
        app: user
spec:
    ports:
        - port: 80
    selector:
        app: user
```

Both pods are starting without errors, but when I try to access the service (from the URL or from within the micro container) I get this error:
```
{"id":"go.micro.api","code":500,"detail":"error during request: all SubConns are in TransientFailure","status":"Internal Server Error"}
```

When I run micro locally, it's all working as expected. Any ideas?

Cheers
