### ISSUE TITLE
Fail to run a kubernetes service. Recieve 403

### ISSUE THREAD

**Issue by zachlefevre** [micro/kubernetes#23]
<img width="959" alt="kub-mic" src="https://user-images.githubusercontent.com/17463558/48168602-8732a000-e2b5-11e8-86b6-0ca3b3149a97.PNG">

Manifest
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: web
spec:
  selector:
    matchLabels:
      name: web
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web
          command: [
            "./web",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
            ]
          image: frlnbrg/web:v0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: greeter-port
```

Service
```
package main

import (
	"net/http"

	"github.com/micro/go-web"
	k8s "github.com/micro/kubernetes/go/web"
)

func main() {
	service := k8s.NewService(
		web.Name("test"),
	)
	service.HandleFunc("/foo", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`howdy there`))
	})

	service.Init()
	service.Run()
}

```

Any help would be greatly appreciated. This happens on minikube as well as kubernetes deployed to AWS

**Comment by zachlefevre** [comment]
I apologize if this question is naive, but are you referring to the micro/kubernetes k8s package, or my actual kubernetes registry?

**Comment by asim** [comment]
We have a k8s registry which updates the pod via the api to provide extra metadata. This registry relies on the kubernetes (minikube and others) local serviceaccount provided in the pod to access the kubernetes api. You need to ensure this configuration is correct.

**Comment by DiederikvandenB** [comment]
I came across the same problem. For future reference, this is how I resolved it.

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-viewer-role
  namespace: "your namespace"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "pod-viewer-role-binding"
  namespace: "your namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "pod-viewer-role"
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: "default"
  namespace: "your namespace"
```

Make sure that you replace `"your-namespace"` with the correct value.
