### ISSUE TITLE
Can not register micro when different namespace

### ISSUE THREAD

**Issue by eneoti** [micro/kubernetes#34]
I deploy micro-api, micro-web, micro-proxy with namespace "micro" and rbac following:
rbac.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-viewer-role
  namespace: micro
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "pod-viewer-role-binding"
  namespace: micro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "pod-viewer-role"
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: "default"
  namespace: micro
```
Then I try to deploy a micro service.
If this micro is on the same namespace: "micro" . It's work ( this service can be list in registry page of micro-web)
Then I try to change the deployment of this service in another namespace ( also add rbac for new namespace). I can not found it in registry page.
Is it mean that all micro must be the same namespace with namespace of micro-api , micro-web, micro-proxy?
